// Public Google Maps reviews captured on 2026-10-08. Preserve attribution,
// original ratings and short verbatim excerpts. This is not a live feed.
export const googleReviewSnapshot = {
  source: 'google-local' as const,
  capturedAt: '2026-10-08',
  capturedAtLabel: '8 October 2026',
  rating: 4.8,
  userRatingCount: 343,
  googleMapsUri: 'https://www.google.com/maps?cid=10359272721695672749',
  reviews: [
    { author: 'Shehla ashfaq', rating: 5, published: '3 months before capture', profileId: '102274435670029121069', excerpt: 'Dr. Saman is extremely polite and professional. She listened to all my concerns patiently, explained the treatment in detail…' },
    { author: 'Alina Shaffi', rating: 5, published: '6 months before capture', profileId: '103045983848154067131', excerpt: 'I had a great experience with Dr. Saman. She’s incredibly kind, friendly, and genuinely cares about her patients.' },
    { author: 'rafeh rehman', rating: 5, published: '3 months before capture', profileId: '114645724166996101050', excerpt: 'Excellent experience. The dermatologist was professional and knowledgeable. They explained everything clearly and recommended an effective treatment plan.' },
    { author: 'Sarah Ahsan', rating: 5, published: 'Edited 5 months before capture', profileId: '101194930147328299511', excerpt: "I started visiting them in Feb for PCOs acne and laser treatment. It's been 2 months and I have seen a remarkable difference…" },
    { author: 'zoya ali', rating: 5, published: '3 months before capture', profileId: '104906678828627476480', excerpt: 'I had a cautery procedure done by Dr. Suman at Derma Bliss, and my experience was excellent.' },
    { author: 'Talha Raheem', rating: 5, published: '2 months before capture', profileId: '115868702090593902898', excerpt: "The experience was excellent. I received acne treatment along with chemical peel, and I'm very happy with the results." },
    { author: 'Malaika khan', rating: 5, published: '5 months before capture', profileId: '109687958288490107905', excerpt: 'Great experience at derma bliss facial laser clinic! In F7 They are Clean, professional, and very comfortable.' },
    { author: 'Gull Altaf', rating: 5, published: '8 months before capture', profileId: '110338474547463527108', excerpt: 'I had amazing experience here. Dr.Saman knows her job from consultation to treatment.' },
    { author: 'Shajiha 02', rating: 5, published: '2 months before capture', profileId: '106688726240268348302', excerpt: "I had a wonderful experience with Dr saman Excellent dermatologist! Very professional, kind, and knowledgeable. She's amazing Highly recommend!" },
    { author: 'Eiman Ansari', rating: 5, published: '7 months before capture', profileId: '117527948989276657954', excerpt: 'My experience was amazing. Nazia did my hyderfacial while ummia did my laser. They were thorough and careful. Loved it.' },
    { author: 'user 7347', rating: 1, published: '4 months before capture', profileId: '106469140956981179415', excerpt: 'dr saman herself is a respectable doctor, her staff however is immensely unprofessional.' },
    { author: 'Momina Raheem', rating: 5, published: '2 months before capture', profileId: '112955315585500806639', excerpt: 'Dr Saman is very cooperative and listens to your concerns with patience and great understanding.' },
    { author: 'zobia mehrban', rating: 5, published: '1 year before capture', profileId: '114922576205333429117', excerpt: 'I had an excellent experience at Derma Bliss Clinic. The main doctor, Dr. Saman, is truly the best professional…' },
    { author: 'N K', rating: 5, published: '7 months before capture', profileId: '113731648258017768942', excerpt: 'I have had a great experience here. Dr Saman knows her job really well and the staff is also very competent.' },
    { author: 'Mohsin Ejaz', rating: 5, published: '1 year before capture', profileId: '102003692142585133398', excerpt: 'I had an amazing experience at DermaBliss Clinic with Dr. Saman Waseem best skin specialist.' },
    { author: 'Manahil Anil', rating: 5, published: '9 months before capture', profileId: '107061539472307492674', excerpt: 'A huge thanks to all the cooperative staff.' },
    { author: 'muhammad adeem', rating: 4, published: '1 year before capture', profileId: '108168676434687415023', excerpt: 'I recently visited Dr Saman Waseem for an aesthetic treatment, and I couldn’t be more pleased with the experience.' },
    { author: 'Mania Kayani', rating: 5, published: '1 year before capture', profileId: '114885984068717536098', excerpt: 'Dr. Saman Waseem is an exceptional dermatologist. From the moment I walked into her clinic, I felt at ease.' },
    { author: 'affaf nadeem', rating: 1, published: '1 year before capture', profileId: '103220791393195575414', excerpt: 'I had a very disappointing experience with this clinic and unfortunately cannot recommend them due to the lack of professionalism and communication.' },
    { author: 'Mahnoor Tanweer', rating: 5, published: '4 months before capture', profileId: '117847651600339077821', excerpt: 'Its been a wonderful experience. Dr Saman is exceptional and the environment is really good.' },
  ],
};
